version: '3.8'

services:
  php:
    build: .
    container_name: php-container
    volumes:
      - .:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - php
